### ISSUE TITLE
Исправить W3C ошибки и предупреждения

### ISSUE THREAD

**Issue by Mavludin** [Mavludin/intense-it-page#19]
Проверить сайт [https://intense-it.tech/ ](https://intense-it.tech/ )на валидацию здесь [https://validator.w3.org/.](https://validator.w3.org/.)

Исправить ошибки и предупреждения.

**Comment by Bolaji06** [comment]
Привет @Mavludin Я проверил веб-сайт и обнаружил более 80 ошибок и предупреждений. Работа над этим займет некоторое время, но выполнима. Я могу уделить немного времени работе над ними, если вы не возражаете.

**Comment by Mavludin** [comment]
@Bolaji06 Привет! Давай, буду благодарен. Только создай новую ветку от ветки `develop` и затем при завершении работы, открой PR из своей ветки на `develop` и отметь меня как `Reviewer`.

**Comment by Bolaji06** [comment]
Хорошо! Без проблем. Я буду работать над этим, как только смогу. Спасибо, что позволили мне поработать над этим.

**Comment by Mavludin** [comment]
@Bolaji06 You can write in English as well if it's more comfortable for you.

**Comment by Bolaji06** [comment]
Sent a PR
